### ISSUE TITLE
Error: No pubspec.yaml file found  with bitrise.io

### ISSUE THREAD

**Issue by dfang** [DroidsOnRoids/bitrise-step-flutter#11]
bitrise.yml

```
---
format_version: '6'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter
app:
  envs:
  - FLUTTER_COMMANDS: doctor --android-licenses|config --no-analytics|test
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - flutter:
        inputs:
        - version: 1.0.0-stable
        - commands: test
```

works in local macOS, but on bitrise.io

```
Agent version:	0.6.1
Start time:	2018-12-20T09:20:18Z
$ bitrise "run" "--config" "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise-agent191417272/bitrise.yml" "--inventory" "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise-agent191417272/bitrise.secrets.yml" "--json-params-base64" "eyJ3b3JrZmxvdyI6InByaW1hcnkifQ=="
  ██████╗ ██╗████████╗██████╗ ██╗███████╗███████╗
  ██╔══██╗██║╚══██╔══╝██╔══██╗██║██╔════╝██╔════╝
  ██████╔╝██║   ██║   ██████╔╝██║███████╗█████╗
  ██╔══██╗██║   ██║   ██╔══██╗██║╚════██║██╔══╝
  ██████╔╝██║   ██║   ██║  ██║██║███████║███████╗
  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝
  version: 1.25.0

...........

Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
Flutter invocation failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | flutter (exit code: 3)                                        | 34 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/DroidsOnRoids/bitrise-step-flutter/issues  |
| Source: https://github.com/DroidsOnRoids/bitrise
```

is there any guide to setup flutter step in bitrise.io

thansk !
